// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebook.proto

package com.example.online;

public final class Ebook {
  private Ebook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_OrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013ebook.proto\022\tecommerce\":\n\014OrderRequest" +
      "\022*\n\rorderCategory\030\001 \001(\0162\023.ecommerce.Cate" +
      "gory\"7\n\rOrderResponse\022&\n\013orderStatus\030\001 \001" +
      "(\0162\021.ecommerce.Status*\'\n\010Category\022\017\n\013ELE" +
      "CTRONICS\020\000\022\n\n\006EBOOKS\020\001*P\n\006Status\022\024\n\020PAYM" +
      "ENT_RECEIVED\020\000\022\013\n\007SHIPPED\020\001\022\024\n\020OUT_FOR_D" +
      "ELIVERY\020\002\022\r\n\tDELIVERED\020\0032R\n\rOnlineServic" +
      "e\022A\n\nplaceOrder\022\027.ecommerce.OrderRequest" +
      "\032\030.ecommerce.OrderResponse0\001B\026\n\022com.exam" +
      "ple.onlineP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ecommerce_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ecommerce_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_OrderRequest_descriptor,
        new java.lang.String[] { "OrderCategory", });
    internal_static_ecommerce_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ecommerce_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_OrderResponse_descriptor,
        new java.lang.String[] { "OrderStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
