// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebook.proto

package com.example.online;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ecommerce.Status orderStatus = 1;</code>
   */
  int getOrderStatusValue();
  /**
   * <code>.ecommerce.Status orderStatus = 1;</code>
   */
  com.example.online.Status getOrderStatus();
}
