// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebook.proto

package com.example.online;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ecommerce.Category orderCategory = 1;</code>
   */
  int getOrderCategoryValue();
  /**
   * <code>.ecommerce.Category orderCategory = 1;</code>
   */
  com.example.online.Category getOrderCategory();
}
