// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebook.proto

package com.example.online;

/**
 * Protobuf enum {@code ecommerce.Status}
 */
public enum Status
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PAYMENT_RECEIVED = 0;</code>
   */
  PAYMENT_RECEIVED(0),
  /**
   * <code>SHIPPED = 1;</code>
   */
  SHIPPED(1),
  /**
   * <code>OUT_FOR_DELIVERY = 2;</code>
   */
  OUT_FOR_DELIVERY(2),
  /**
   * <code>DELIVERED = 3;</code>
   */
  DELIVERED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PAYMENT_RECEIVED = 0;</code>
   */
  public static final int PAYMENT_RECEIVED_VALUE = 0;
  /**
   * <code>SHIPPED = 1;</code>
   */
  public static final int SHIPPED_VALUE = 1;
  /**
   * <code>OUT_FOR_DELIVERY = 2;</code>
   */
  public static final int OUT_FOR_DELIVERY_VALUE = 2;
  /**
   * <code>DELIVERED = 3;</code>
   */
  public static final int DELIVERED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Status valueOf(int value) {
    return forNumber(value);
  }

  public static Status forNumber(int value) {
    switch (value) {
      case 0: return PAYMENT_RECEIVED;
      case 1: return SHIPPED;
      case 2: return OUT_FOR_DELIVERY;
      case 3: return DELIVERED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Status>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Status> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Status>() {
          public Status findValueByNumber(int number) {
            return Status.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.example.online.Ebook.getDescriptor().getEnumTypes().get(1);
  }

  private static final Status[] VALUES = values();

  public static Status valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ecommerce.Status)
}

