// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.example.calculator;

public interface InputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.Input)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
