// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.example.calculator;

public interface OutputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.Output)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 result = 1;</code>
   */
  long getResult();
}
