// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gps.proto

package com.example.gps;

public final class Gps {
  private Gps() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gps_GPSRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gps_GPSRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gps_GPSResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gps_GPSResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tgps.proto\022\003gps\"\'\n\nGPSRequest\022\031\n\021distan" +
      "ceTravelled\030\001 \001(\005\"C\n\013GPSResponse\022\031\n\021rema" +
      "iningDistance\030\001 \001(\005\022\031\n\021timeToDestination" +
      "\030\002 \001(\0052F\n\021NavigationService\0221\n\010navigate\022" +
      "\017.gps.GPSRequest\032\020.gps.GPSResponse(\0010\001B\023" +
      "\n\017com.example.gpsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gps_GPSRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gps_GPSRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gps_GPSRequest_descriptor,
        new java.lang.String[] { "DistanceTravelled", });
    internal_static_gps_GPSResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gps_GPSResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gps_GPSResponse_descriptor,
        new java.lang.String[] { "RemainingDistance", "TimeToDestination", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
