// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gps.proto

package com.example.gps;

public interface GPSResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gps.GPSResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 remainingDistance = 1;</code>
   */
  int getRemainingDistance();

  /**
   * <code>int32 timeToDestination = 2;</code>
   */
  int getTimeToDestination();
}
