// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gps.proto

package com.example.gps;

public interface GPSRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gps.GPSRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 distanceTravelled = 1;</code>
   */
  int getDistanceTravelled();
}
